/*
 * This source file was generated by the Gradle 'init' task
 */
package org.racketsimulator;

import org.racketsimulator.expressionbuilder.ExpressionBuilder;

public class App {
    public static void main(String[] args) {
        Configuration config = new Configuration();
        ExpressionBuilder entranceParser = config.entranceParser();
        System.out.println("Funca");
    }
}
